<h2 id="Contents">Contents<a href="#Contents"></a></h2>
        <ol>
        <li><a class="" href="#Array">Array</a></li>
<ol><li><a class="" href="#Numeric-Sort">Numeric Sort</a></li>
<li><a class="" href="#Min-and-Max-of-an-Array">Min and Max of an Array</a></li>
</ol><li><a class="" href="#String">String</a></li>
<li><a class="" href="#Number">Number</a></li>
<li><a class="" href="#Math">Math</a></li>
<li><a class="" href="#Date-Methods">Date Methods</a></li>
<li><a class="" href="#JavaScript-Type-Conversion">JavaScript Type Conversion</a></li>
<ol><li><a class="" href="#Converting-Strings-to-Numbers">Converting Strings to Numbers</a></li>
<li><a class="" href="#Converting-Numbers-to-Strings">Converting Numbers to Strings</a></li>
<li><a class="" href="#Converting-Dates-to-Numbers-and-Strings">Converting Dates to Numbers and Strings</a></li>
<li><a class="" href="#Converting-Booleans-to-Numbers-and-Strings">Converting Booleans to Numbers and Strings</a></li>
<li><a class="" href="#Automatic-Type-Conversion">Automatic Type Conversion</a></li>
</ol>

# Array

<table>
  <tbody><tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>concat()</code></td>
    <td>Joins arrays and returns an array with the joined arrays</td>
  </tr>
  <tr>
    <td><code>constructor</code></td>
    <td>Returns the function that created the Array object's prototype</td>
  </tr>
  <tr>
    <td><code>copyWithin()</code></td>
    <td>Copies array elements within the array, to and from specified positions</td>
  </tr>
  <tr>
    <td><code>entries()</code></td>
    <td>Returns a key/value pair Array Iteration Object</td>
    </tr>
  <tr>
    <td><code>every()</code></td>
    <td>Checks if every element in an array pass a test</td>
    </tr>
    <tr>
    <td><code>fill()</code></td>
    <td>Fill the elements in an array with a static value</td>
    </tr>
    <tr>
    <td><code>filter()</code></td>
    <td>Creates a new array with every element in an array that pass a test</td>
    </tr>
    <tr>
    <td><code>find()</code></td>
    <td>Returns the value of the first element in an array that pass a test</td>
    </tr>
    <tr>
    <td><code>findIndex()</code></td>
    <td>Returns the index of the first element in an array that pass a test</td>
    </tr>
  <tr>
    <td><code>forEach()</code></td>
    <td>Calls a function for each array element</td>
    </tr>
  <tr>
    <td><code>from()</code></td>
    <td>Creates an array from an object</td>
    </tr>
  <tr>
    <td><code>includes()</code></td>
    <td>Check if an array contains the specified element</td>
    </tr>
    <tr>
    <td><code>indexOf()</code></td>
    <td>Search the array for an element and returns its position</td>
    </tr>
  <tr>
    <td><code>isArray()</code></td>
    <td>Checks whether an object is an array</td>
    </tr>
  <tr>
    <td><code>join()</code></td>
    <td>Joins all elements of an array into a string</td>
    </tr>
  <tr>
    <td><code>keys()</code></td>
    <td>Returns a Array Iteration Object, containing the keys of the original array</td>
    </tr>
  <tr>
    <td><code>lastIndexOf()</code></td>
    <td>Search the array for an element, starting at the end, and returns its position</td>
    </tr>
  <tr>
    <td><code>length</code></td>
    <td>Sets or returns the number of elements in an array</td>
  </tr>
    <tr>
    <td><code>map()</code></td>
    <td>Creates a new array with the result of calling a function for each array element</td>
    </tr>
  <tr>
    <td><code>pop()</code></td>
    <td>Removes the last element of an array, and returns that element</td>
    </tr>
  <tr>
    <td><code>prototype</code></td>
    <td>Allows you to add properties and methods to an Array object</td>
  </tr>
  <tr>
    <td><code>push()</code></td>
    <td>Adds new elements to the end of an array, and returns the new length</td>
    </tr>
    <tr>
    <td><code>reduce()</code></td>
    <td>Reduce the values of an array to a single value (going left-to-right)</td>
    </tr>
    <tr>
    <td><code>reduceRight()</code></td>
    <td>Reduce the values of an array to a single value (going right-to-left)</td>
    </tr>
  <tr>
    <td><code>reverse()</code></td>
    <td>Reverses the order of the elements in an array</td>
    </tr>
  <tr>
    <td><code>shift()</code></td>
    <td>Removes the first element of an array, and returns that element</td>
    </tr>
  <tr>
    <td><code>slice()</code></td>
    <td>Selects a part of an array, and returns the new array</td>
    </tr>
  <tr>
    <td><code>some()</code></td>
    <td>Checks if any of the elements in an array pass a test</td>
    </tr>
  <tr>
    <td><code>sort()</code></td>
    <td>Sorts the elements of an array</td>
    </tr>
  <tr>
    <td><code>splice()</code></td>
    <td>Adds/Removes elements from an array</td>
    </tr>
  <tr>
    <td><code>toString()</code></td>
    <td>Converts an array to a string, and returns the result</td>
    </tr>
  <tr>
    <td><code>unshift()</code></td>
    <td>Adds new elements to the beginning of an array, and returns the new length</td>
    </tr>
  <tr>
    <td><code>valueOf()</code></td>
    <td>Returns the primitive value of an array</td>
    </tr>
</tbody></table>

## Numeric Sort

By default, the `sort()` function sorts values as strings. This works well for strings ("Apple" comes before "Banana"). However, if numbers are sorted as strings, "25" is bigger than "100", because "2" is bigger than "1". Because of this, the `sort()` method will produce incorrect result when sorting numbers. You can fix this by providing a compare function:

```js
const points = [40, 100, 1, 5, 25, 10];
points.sort(function (a, b) {
  return a - b;
});
```

Use the same trick to sort an array descending:

```js
const points = [40, 100, 1, 5, 25, 10];
points.sort(function (a, b) {
  return b - a;
});
```

## Min and Max of an Array

The `Math.min` and `Math.max` functions can take any number of arguments, and return the lowest or highest value. However, if you have an array of values, you can use the `spread operator` to find the lowest or highest value:

```js
const points = [40, 100, 1, 5, 25, 10];
const lowest = Math.min(...points);
const highest = Math.max(...points);
```

# String

<table class="ws-table-all notranslate">
  <tbody><tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>charAt()</code></td>
    <td>Returns the character at a specified index (position)</td>
  </tr>
  <tr>
    <td><code>charCodeAt()</code></td>
    <td>Returns the Unicode of the character at a specified index</td>
  </tr>
  <tr>
    <td><code>concat()</code></td>
    <td>Returns two or more joined strings</td>
  </tr>
  <tr>
    <td><code>constructor</code></td>
    <td>Returns the string's constructor function</td>
  </tr>
  <tr>
    <td><code>endsWith()</code></td>
    <td>Returns if a string ends with a specified value</td>
  </tr>
  <tr>
    <td><code>fromCharCode()</code></td>
    <td>Returns Unicode values as characters</td>
  </tr>
    <tr>
    <td><code>includes()</code></td>
    <td>Returns if a string contains a specified value</td>
    </tr>
  <tr>
    <td><code>indexOf()</code></td>
    <td>Returns the index (position) of the first occurrence of a value in a string</td>
  </tr>
  <tr>
    <td><code>lastIndexOf()</code></td>
    <td>Returns the index (position) of the last occurrence of a value in a string</td>
  </tr>
  <tr>
    <td><code>length</code></td>
    <td>Returns the length of a string</td>
  </tr>
  <tr>
    <td><code>localeCompare()</code></td>
    <td>Compares two strings in the current locale</td>
  </tr>
  <tr>
    <td><code>match()</code></td>
    <td>Searches a string for a value, or a regular expression, and returns the matches</td>
  </tr>
  <tr>
    <td><code>prototype</code></td>
    <td>Allows you to add properties and methods to an object</td>
  </tr>
    <tr>
    <td><code>repeat()</code></td>
    <td>Returns a new string with a number of copies of a string</td>
    </tr>
  <tr>
    <td><code>replace()</code></td>
    <td>Searches a string for a value, or a regular expression, and returns a string where the values are replaced</td>
  </tr>
  <tr>
    <td><code>search()</code></td>
    <td>Searches a string for a value, or regular expression, and returns the index (position) of the match</td>
  </tr>
  <tr>
    <td><code>slice()</code></td>
    <td>Extracts a part of a string and returns a new string</td>
  </tr>
    <tr>
    <td><code>split()</code></td>
    <td>Splits a string into an array of substrings</td>
    </tr>
  <tr>
    <td><code>startsWith()</code></td>
    <td>Checks whether a string begins with specified characters</td>
  </tr>
  <tr>
    <td><code>substr()</code></td>
    <td>Extracts a number of characters from a string, from a start index (position)</td>
  </tr>
  <tr>
    <td><code>substring()</code></td>
    <td>Extracts characters from a string, between two specified indices (positions)</td>
  </tr>
  <tr>
    <td><code>toLocaleLowerCase()</code></td>
    <td>Returns a string converted to lowercase letters, using the host's locale</td>
  </tr>
  <tr>
    <td><code>toLocaleUpperCase()</code></td>
    <td>Returns a string converted to uppercase letters, using the host's locale</td>
  </tr>
  <tr>
    <td><code>toLowerCase()</code></td>
    <td>Returns a string converted to lowercase letters</td>
  </tr>
  <tr>
    <td><code>toString()</code></td>
    <td>Returns a string or a string object as a string</td>
  </tr>
  <tr>
    <td><code>toUpperCase()</code></td>
    <td>Returns a string converted to uppercase letters</td>
  </tr>
  <tr>
    <td><code>trim()</code></td>
    <td>Returns a string with removed whitespaces</td>
  </tr>
  <tr>
    <td><code>trimEnd()</code></td>
    <td>Returns a string with removed whitespaces from the end</td>
  </tr>
  <tr>
    <td><code>trimStart()</code></td>
    <td>Returns a string with removed whitespaces from the start</td>
  </tr>
  <tr>
    <td><code>valueOf()</code></td>
    <td>Returns the primitive value of a string or a string object</td>
  </tr>
</tbody></table>

# Number

<table class="ws-table-all notranslate">
  <tbody><tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>constructor</code></td>
    <td>Returns the function that created JavaScript's Number prototype</td>
  </tr>
  <tr>
    <td><code>isFinite()</code></td>
    <td>Checks whether a value is a finite number</td>
  </tr>
  <tr>
    <td><code>isInteger()</code></td>
    <td>Checks whether a value is an integer</td>
  </tr>
  <tr>
    <td><code>isNaN()</code></td>
    <td>Checks whether a value is Number.NaN</td>
  </tr>
  <tr>
    <td><code>isSafeInteger()</code></td>
    <td>Checks whether a value is a safe integer</td>
  </tr>
  <tr>
    <td><code>MAX_VALUE</code></td>
    <td>Returns the largest number possible in JavaScript</td>
  </tr>
  <tr>
    <td><code>MIN_VALUE</code></td>
    <td>Returns the smallest number possible in JavaScript</td>
  </tr>
  <tr>
    <td><code>NEGATIVE_INFINITY</code></td>
    <td>Represents negative infinity (returned on overflow)</td>
    </tr>
  <tr>
    <td><code>NaN</code></td>
    <td>Represents a "Not-a-Number" value</td>
    </tr>
  <tr>
    <td><code>POSITIVE_INFINITY</code></td>
    <td>Represents infinity (returned on overflow)</td>
  </tr>
  <tr>
    <td><code>prototype</code></td>
    <td>Allows you to add properties and methods to an object</td>
  </tr>
  <tr>
    <td><code>toExponential(x)</code></td>
    <td>Converts a number into an exponential notation</td>
  </tr>
  <tr>
    <td><code>toFixed(x)</code></td>
    <td>Formats a number with x numbers of digits after the decimal point</td>
  </tr>
  <tr>
    <td><code>toLocaleString()</code></td>
    <td>Converts a number into a string, based on the locale settings</td>
  </tr>
  <tr>
    <td><code>toPrecision(x)</code></td>
    <td>Formats a number to x length</td>
  </tr>
  <tr>
    <td><code>toString()</code></td>
    <td>Converts a number to a string</td>
  </tr>
  <tr>
    <td><code>valueOf()</code></td>
    <td>Returns the primitive value of a number</td>
  </tr>
 </tbody></table>

# Math

<table class="ws-table-all notranslate">
  <tbody><tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>abs(x)</code></td>
    <td>Returns the absolute value of x</td>
  </tr>
  <tr>
    <td><code>acos(x)</code></td>
    <td>Returns the arccosine of x, in radians</td>
  </tr>
  <tr>
    <td><code>acosh(x)</code></td>
    <td>Returns the hyperbolic arccosine of x</td>
  </tr>
  <tr>
    <td><code>asin(x)</code></td>
    <td>Returns the arcsine of x, in radians</td>
  </tr>
  <tr>
    <td><code>asinh(x)</code></td>
    <td>Returns the hyperbolic arcsine of x</td>
  </tr>
  <tr>
    <td><code>atan(x)</code></td>
    <td>Returns the arctangent of x as a numeric value between -PI/2 and PI/2 radians</td>
  </tr>
  <tr>
    <td><code>atan2(y, x)</code></td>
    <td>Returns the arctangent of the quotient of its arguments</td>
  </tr>
  <tr>
    <td><code>atanh(x)</code></td>
    <td>Returns the hyperbolic arctangent of x</td>
  </tr>
  <tr>
    <td><code>cbrt(x)</code></td>
    <td>Returns the cubic root of x</td>
  </tr>
  <tr>
    <td><code>ceil(x)</code></td>
    <td>Returns x, rounded upwards to the nearest integer</td>
  </tr>
  <tr>
    <td><code>clz32(x)</code></td>
    <td>Returns the number of leading zeros in a 32-bit binary representation of x</td>
  </tr>
  <tr>
    <td><code>cos(x)</code></td>
    <td>Returns the cosine of x (x is in radians)</td>
  </tr>
  <tr>
    <td><code>cosh(x)</code></td>
    <td>Returns the hyperbolic cosine of x</td>
  </tr>
  <tr>
    <td><code>E</code></td>
    <td>Returns Euler's number (approx. 2.718)</td>
  </tr>
  <tr>
    <td><code>exp(x)</code></td>
    <td>Returns the value of E<sup>x</sup></td>
  </tr>
  <tr>
    <td><code>expm1(x)</code></td>
    <td>Returns the value of E<sup>x</sup> minus 1</td>
  </tr>
  <tr>
    <td><code>floor(x)</code></td>
    <td>Returns x, rounded downwards to the nearest integer</td>
  </tr>
  <tr>
    <td><code>fround(x)</code></td>
    <td>Returns the nearest (32-bit single precision) float representation of a number</td>
  </tr>
  <tr>
    <td><code>LN2</code></td>
    <td>Returns the natural logarithm of 2 (approx. 0.693)</td>
  </tr>
  <tr>
    <td><code>LN10</code></td>
    <td>Returns the natural logarithm of 10 (approx. 2.302)</td>
  </tr>
  <tr>
    <td><code>log(x)</code></td>
    <td>Returns the natural logarithmof x</td>
  </tr>
  <tr>
    <td><code>log10(x)</code></td>
    <td>Returns the base-10 logarithm of x</td>
  </tr>
  <tr>
    <td><code>LOG10E</code></td>
    <td>Returns the base-10 logarithm of E (approx. 0.434)</td>
  </tr>
  <tr>
    <td><code>log1p(x)</code></td>
    <td>Returns the natural logarithm of 1 + x</td>
  </tr>
  <tr>
    <td><code>log2(x)</code></td>
    <td>Returns the base-2 logarithm of x</td>
  </tr>
  <tr>
    <td><code>LOG2E</code></td>
    <td>Returns the base-2 logarithm of E (approx. 1.442)</td>
  </tr>
  <tr>
    <td><code>max(x1,x2,..)</code></td>
    <td>Returns the number with the highest value</td>
  </tr>
  <tr>
    <td><code>min(x1,x2,..)</code></td>
    <td>Returns the number with the lowest value</td>
  </tr>
  <tr>
    <td><code>PI</code></td>
    <td>Returns PI (approx. 3.14)</td>
  </tr>
  <tr>
    <td><code>pow(x, y)</code></td>
    <td>Returns the value of x to the power of y</td>
  </tr>
  <tr>
    <td><code>.*\(\)</code></code></td>
    <td>Returns a random number between 0 and 1</td>
  </tr>
  <tr>
    <td><code>round(x)</code></td>
    <td>Rounds x to the nearest integer</td>
  </tr>
  <tr>
    <td><code>sign(x)</code></td>
    <td>Returns the sign of a number (checks whether it is positive, negative or zero)</td>
  </tr>
  <tr>
    <td><code>sin(x)</code></td>
    <td>Returns the sine of x (x is in radians)</td>
  </tr>
  <tr>
    <td><code>sinh(x)</code></td>
    <td>Returns the hyperbolic sine of x</td>
  </tr>
  <tr>
    <td><code>sqrt(x)</code></td>
    <td>Returns the square root of x</td>
  </tr>
  <tr>
    <td><code>SQRT1_2</code></td>
    <td>Returns the square root of 1/2 (approx. 0.707)</td>
  </tr>
  <tr>
    <td><code>SQRT2</code></td>
    <td>Returns the square root of 2 (approx. 1.414)</td>
  </tr>
  <tr>
    <td><code>tan(x)</code></td>
    <td>Returns the tangent of an angle</td>
  </tr>
  <tr>
    <td><code>tanh(x)</code></td>
    <td>Returns the hyperbolic tangent of a number</td>
  </tr>
  <tr>
    <td><code>trunc(x)</code></td>
    <td>Returns the integer part of a number (x)</td>
  </tr>
  </tbody></table>

# Date Methods

<table>
<tbody><tr>
<th>Method</th>
<th>Description</th>
</tr>
<tr>
<td>getDate()</td>
<td>Get the day as a number (1-31)</td>
</tr>
<tr>
<td>getDay()</td>
<td>Get the weekday a number (0-6)</td>
</tr>
<tr>
<td>getFullYear()</td>
<td>Get the four digit year (yyyy)</td>
</tr>
<tr>
<td>getHours()</td>
<td>Get the hour (0-23)</td>
</tr>
<tr>
<td>getMilliseconds()</td>
<td>Get the milliseconds (0-999)</td>
</tr>
<tr>
<td>getMinutes()</td>
<td>Get the minutes (0-59)</td>
</tr>
<tr>
<td>getMonth()</td>
<td>Get the month (0-11)</td>
</tr>
<tr>
<td>getSeconds()</td>
<td>Get the seconds (0-59)</td>
</tr>
<tr>
<td>getTime()</td>
<td>Get the time (milliseconds since January 1, 1970)</td>
</tr>
</tbody></table>

# JavaScript Type Conversion

## Converting Strings to Numbers

The global method `Number()` converts a variable (or a value) into a number.

A numeric string (like "3.14") converts to a number (like 3.14).

An empty string (like "") converts to 0.

A non numeric string (like "John") converts to `NaN` (Not a Number).

These will convert:

```javascript
Number("3.14");
Number(Math.PI);
Number(" ");
Number("");
```

These will not convert:

```javascript
Number("John");
Number("99 88");
```

Here are some number methods to parse float and int.

<table class="ws-table-all notranslate">
  <tbody><tr>
    <th>Method</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>.*\(\)</code></td>
    <td>Returns a number, converted from its argument</td>
    </tr>
  <tr>
  </tr><tr>
    <td><code>.*\(\)</code></td>
    <td>Parses a string and returns a floating point number</td>
    </tr>
  <tr>
    <td><code>.*\(\)</code></td>
    <td>Parses a string and returns an integer</td>
    </tr>
</tbody></table>

## Converting Numbers to Strings

The global method `String()` can convert numbers to strings.

It can be used on any type of numbers, literals, variables, or expressions. The Number method `toString()` does the same.

```javascript
String(x); // returns a string from a number variable x
String(123); // returns a string from a number literal 123
String(100 + 23); // returns a string from a number from an expression

x.toString()(123)
  .toString()(100 + 23)
  .toString();
```

Here are some more methods that can convert numbers to strings:

<table class="ws-table-all notranslate">
  <tbody><tr>
    <th style="width:25%">Method</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><code>.*\(\)</code></td>
    <td>Returns a string, with a number rounded and written using exponential notation.</td>
  </tr>
  <tr>
    <td><code>.*\(\)</code></td>
    <td>Returns a string, with a number rounded and written with a specified number of decimals.</td>
  </tr>
  <tr>
    <td><code>.*\(\)</code></td>
    <td>Returns a string, with a number written with a specified length</td>
  </tr>
</tbody></table>

## Converting Dates to Numbers and Strings

Using the global method `Number()` and `String()` can convert dates to numbers and strings.

```javascript
d = new Date();
Number(d); // returns 1404568027739

String(Date()); // returns "Thu Jul 17 2014 15:38:19 GMT+0200 (W. Europe Daylight Time)"
```

The date method `getTime()` does the same.

```javascript
d = new Date();
d.getTime();
```

The Date method `toString()` does the same.

```javascript
Date().toString(); // returns "Thu Jul 17 2014 15:38:19 GMT+0200 (W. Europe Daylight Time)"
```

## Converting Booleans to Numbers and Strings

The global method `Number()` can also convert booleans to numbers.

```javascript
Number(false); // returns 0
Number(true); // returns 1
```

The global method `String()` can convert booleans to strings.

```javascript
String(false); // returns "false"
String(true); // returns "true"
```

The Boolean method `toString()` does the same.

```javascript
false.toString(); // returns "false"
true.toString(); // returns "true"
```

## Automatic Type Conversion

When JavaScript tries to operate on a "wrong" data type, it will try to convert the value to a "right" type.

The result is not always what you expect:

```javascript
5 + null; // returns 5         because null is converted to 0
"5" + null; // returns "5null"   because null is converted to "null"
"5" + 2; // returns "52"      because 2 is converted to "2"
"5" - 2; // returns 3         because "5" is converted to 5
"5" * "2"; // returns 10        because "5" and "2" are converted to 5 and 2
```

Here is a table of some conversions:

<table>
 <tbody><tr>
  <th>Original<br>Value</th>
  <th>Converted<br>to Number</th>
  <th>Converted<br>to String</th>
  <th>Converted<br>to Boolean</th>
 </tr>
 <tr>
  <td>false</td>
  <td>0</td>
  <td>"false"</td>
  <td>false</td>
  
 </tr>
 <tr>
  <td>true</td>
  <td>1</td>
  <td>"true"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>0</td>
  <td>0</td>
  <td>"0"</td>
  <td>false</td>
  
 </tr>
 <tr>
  <td>1</td>
  <td>1</td>
  <td>"1"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>"0"</td>
  <td>0</td>
  <td>"0"</td>
  <td style="color:red;">true</td>
  
 </tr>
 <tr>
  <td>"000"</td>
  <td>0</td>
  <td>"000"</td>
  <td style="color:red;">true</td>
  
 </tr>
 <tr>
  <td>"1"</td>
  <td>1</td>
  <td>"1"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>NaN</td>
  <td>NaN</td>
  <td>"NaN"</td>
  <td>false</td>
  
 </tr>
 <tr>
  <td>Infinity</td>
  <td>Infinity</td>
  <td>"Infinity"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>-Infinity</td>
  <td>-Infinity</td>
  <td>"-Infinity"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>""</td>
  <td style="color:red;">0</td>
  <td>""</td>
  <td style="color:red;">false</td>
  
 </tr>
 <tr>
  <td>"20"</td>
  <td>20</td>
  <td>"20"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>"twenty"</td>
  <td>NaN</td>
  <td>"twenty"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>[ ]</td>
  <td style="color:red;">0</td>
  <td>""</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>[20]</td>
  <td style="color:red;">20</td>
  <td>"20"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>[10,20]</td>
  <td>NaN</td>
  <td>"10,20"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>["twenty"]</td>
  <td>NaN</td>
  <td>"twenty"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>["ten","twenty"]</td>
  <td>NaN</td>
  <td>"ten,twenty"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>function(){}</td>
  <td>NaN</td>
  <td>"function(){}"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>{ }</td>
  <td>NaN</td>
  <td>"[object Object]"</td>
  <td>true</td>
  
 </tr>
 <tr>
  <td>null</td>
  <td style="color:red;">0</td>
  <td>"null"</td>
  <td>false</td>
  
 </tr>
 <tr>
  <td>undefined</td>
  <td>NaN</td>
  <td>"undefined"</td>
  <td>false</td>
  
 </tr>
</tbody></table>

Red values indicate values (some) programmers might not expect.