<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be performing data wrangling.

## Objectives

In this lab you will perform the following:

-   Identify duplicate values in the dataset.

-   Remove duplicate values from the dataset.

-   Identify missing values in the dataset.

-   Impute the missing values in the dataset.

-   Normalize data in the dataset.

<hr>

## Hands on Lab

Import pandas module.

In [1]:
import pandas as pd

Load the dataset into a dataframe.

In [13]:
df = pd.read_csv("m1_survey_data.csv")

In [14]:
len(df["Respondent"]) - len(df["Respondent"].drop_duplicates())

154

## Finding duplicates

In this section you will identify duplicate values in the dataset.

 Find how many duplicate rows exist in the dataframe.

In [15]:
# your code goes here
len(df) - len(df.drop_duplicates())

154

## Removing duplicates

Remove the duplicate rows from the dataframe.

In [16]:
# your code goes here
df.drop_duplicates(inplace=True)

Verify if duplicates were actually dropped.

In [17]:
# your code goes here
len(df) - len(df.drop_duplicates())

0

In [18]:
len(df)

11398

In [19]:
df["Respondent"].nunique()

11398

## Finding Missing values

In [23]:
df["EdLevel"].isna().sum()

112

In [24]:
df["Country"].isna().sum()

0

Find the missing values for all columns.

In [20]:
# your code goes here
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11398 entries, 0 to 11551
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Respondent              11398 non-null  int64
 1   MainBranch              11398 non-null  object
 2   Hobbyist                11398 non-null  object
 3   OpenSourcer             11398 non-null  object
 4   OpenSource              11317 non-null  object
 5   Employment              11398 non-null  object
 6   Country                 11398 non-null  object
 7   Student                 11347 non-null  object
 8   EdLevel                 11286 non-null  object
 9   UndergradMajor          10661 non-null  object
 10  EduOther                11234 non-null  object
 11  OrgSize                 11302 non-null  object
 12  DevType                 11333 non-null  object
 13  YearsCode               11389 non-null  object
 14  Age1stCode              11385 non-null  object
 15  YearsCodePro            11382 non-null  object
 16  CareerSat               11398 non-null  object
 17  JobSat                  11397 non-null  object
 18  MgrIdiot                10905 non-null  object
 19  MgrMoney                10901 non-null  object
 20  MgrWant                 10905 non-null  object
 21  JobSeek                 11398 non-null  object
 22  LastHireDate            11398 non-null  object
 23  LastInt                 10985 non-null  object
 24  FizzBuzz                11361 non-null  object
 25  JobFactors              11395 non-null  object
 26  ResumeUpdate            11359 non-null  object
 27  CurrencySymbol          11398 non-null  object
 28  CurrencyDesc            11398 non-null  object
 29  CompTotal               10589 non-null  float64
 30  CompFreq                11192 non-null  object
 31  ConvertedComp           10582 non-null  float64
 32  WorkWeekHrs             11276 non-null  float64
 33  WorkPlan                11277 non-null  object
 34  WorkChallenge           11234 non-null  object
 35  WorkRemote              11390 non-null  object
 36  WorkLoc                 11366 non-null  object
 37  ImpSyn                  11393 non-null  object
 38  CodeRev                 11397 non-null  object
 39  CodeRevHrs              8972 non-null   float64
 40  UnitTests               11369 non-null  object
 41  PurchaseHow             11202 non-null  object
 42  PurchaseWhat            11360 non-null  object
 43  LanguageWorkedWith      11387 non-null  object
 44  LanguageDesireNextYear  11264 non-null  object
 45  DatabaseWorkedWith      10945 non-null  object
 46  DatabaseDesireNextYear  10356 non-null  object
 47  PlatformWorkedWith      10987 non-null  object
 48  PlatformDesireNextYear  10854 non-null  object
 49  WebFrameWorkedWith      10005 non-null  object
 50  WebFrameDesireNextYear  9781 non-null   object
 51  MiscTechWorkedWith      9216 non-null   object
 52  MiscTechDesireNextYear  9943 non-null   object
 53  DevEnviron              11369 non-null  object
 54  OpSys                   11364 non-null  object
 55  Containers              11316 non-null  object
 56  BlockchainOrg           9076 non-null   object
 57  BlockchainIs            8788 non-null   object
 58  BetterLife              11300 non-null  object
 59  ITperson                11363 non-null  object
 60  OffOn                   11360 non-null  object
 61  SocialMedia             11105 non-null  object
 62  Extraversion            11378 non-null  object
 63  ScreenName              10891 non-null  object
 64  SOVisit1st              11073 non-null  object
 65  SOVisitFreq             11393 non-null  object
 66  SOVisitTo               11397 non-null  object
 67  SOFindAnswer            11395 non-null  object
 68  SOTimeSaved             11348 non-null  object
 69  SOHowMuchTime           9481 non-null   object
 70  SOAccount               11397 non-null  object
 71  SOPartFreq              10270 non-null  object
 72  SOJobs                  11392 non-null  object
 73  EntTeams                11393 non-null  object
 74  SOComm                  11398 non-null  object
 75  WelcomeChange           11313 non-null  object
 76  SONewContent            9433 non-null   object
 77  Age                     11111 non-null  float64
 78  Gender                  11325 non-null  object
 79  Trans                   11275 non-null  object
 80  Sexuality               10856 non-null  object
 81  Ethnicity               10723 non-null  object
 82  Dependents              11258 non-null  object
 83  SurveyLength            11379 non-null  object
 84  SurveyEase              11384 non-null  object
dtypes: float64(5), int64(1), object(79)
memory usage: 7.5+ MB

Find out how many rows are missing in the column 'WorkLoc'

In [22]:
# your code goes here
df["WorkLoc"].isna().sum()

32

## Imputing missing values

Find the  value counts for the column WorkLoc.

In [25]:
# your code goes here
df["WorkLoc"].value_counts()

Office                                            6806
Home                                              3589
Other place, such as a coworking space or cafe     971
Name: WorkLoc, dtype: int64

Identify the value that is most frequent (majority) in the WorkLoc column.

In [27]:
#make a note of the majority value here, for future reference
#
df["WorkLoc"].value_counts().index[0]

'Office'

Impute (replace) all the empty rows in the column WorkLoc with the value that you have identified as majority.

In [28]:
# your code goes here
df["WorkLoc"].fillna(df["WorkLoc"].value_counts().index[0], inplace=True)

After imputation there should ideally not be any empty rows in the WorkLoc column.

Verify if imputing was successful.

In [29]:
# your code goes here
df["WorkLoc"].isna().sum()

0

In [30]:
df["Employment"].value_counts()

Employed full-time    10968
Employed part-time      430
Name: Employment, dtype: int64

In [31]:
df["UndergradMajor"].value_counts()

Computer science, computer engineering, or software engineering          6953
Information systems, information technology, or system administration     794
Another engineering discipline (ex. civil, electrical, mechanical)        759
Web development or web design                                             410
A natural science (ex. biology, chemistry, physics)                       403
Mathematics or statistics                                                 372
A business discipline (ex. accounting, finance, marketing)                244
A social science (ex. anthropology, psychology, political science)        210
A humanities discipline (ex. literature, history, philosophy)             207
Fine arts or performing arts (ex. graphic design, music, studio art)      161
I never declared a major                                                  124
A health science (ex. nursing, pharmacy, radiology)                        24
Name: UndergradMajor, dtype: int64

In [32]:
df["ConvertedComp"].describe()

count    1.058200e+04
mean     1.315967e+05
std      2.947865e+05
min      0.000000e+00
25%      2.686800e+04
50%      5.774500e+04
75%      1.000000e+05
max      2.000000e+06
Name: ConvertedComp, dtype: float64

## Normalizing data

There are two columns in the dataset that talk about compensation.

One is "CompFreq". This column shows how often a developer is paid (Yearly, Monthly, Weekly).

The other is "CompTotal". This column talks about how much the developer is paid per Year, Month, or Week depending upon his/her "CompFreq". 

This makes it difficult to compare the total compensation of the developers.

In this section you will create a new column called 'NormalizedAnnualCompensation' which contains the 'Annual Compensation' irrespective of the 'CompFreq'.

Once this column is ready, it makes comparison of salaries easy.

<hr>

List out the various categories in the column 'CompFreq'

In [33]:
# your code goes here
df["CompFreq"].unique()

array(['Yearly', 'Monthly', 'Weekly', nan], dtype=object)

In [34]:
df["CompFreq"].value_counts()

Yearly     6073
Monthly    4788
Weekly      331
Name: CompFreq, dtype: int64

Create a new column named 'NormalizedAnnualCompensation'. Use the hint given below if needed.

Double click to see the **Hint**.

<!--

Use the below logic to arrive at the values for the column NormalizedAnnualCompensation.

If the CompFreq is Yearly then use the exising value in CompTotal
If the CompFreq is Monthly then multiply the value in CompTotal with 12 (months in an year)
If the CompFreq is Weekly then multiply the value in CompTotal with 52 (weeks in an year)

-->

In [35]:
import numpy as np

In [36]:
# your code goes here
normalizer = {
    "Yearly": 1,
    "Monthly": 12,
    "Weekly": 52,
}

def normalize_salary(row):
    if pd.isna(row["ConvertedComp"]):
        return np.nan
    return row["ConvertedComp"] * normalizer[row["CompFreq"]]

In [37]:
df["NormalizedAnnualCompensation"]  = df.apply(normalize_salary, axis=1)
df["NormalizedAnnualCompensation"].median()

110205.0

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).